### ISSUE TITLE
REST endpoint for listing lecture's courses

### ISSUE THREAD

**Issue by gkresic** [vsite-hr/mentor#1]
We need a new endpoint that will return all courses that given lecture is part of:

URL: http://localhost:1800/api/lecture/{lecture-id}/courses
HTTP method: GET
Parameters: None
Response: List of courses.
Example: http://localhost:1800/api/lecture/200ceefa-a476-11e6-aedd-4485006d0fd8/courses

+documentation on GitHub Wiki

**Comment by Genato** [comment]
Finished..
