### ISSUE TITLE
Lecture head unit

### ISSUE THREAD

**Issue by gkresic** [vsite-hr/mentor#11]
Support assigning one Unit as "representative" unit for this Lecture. For example, its thumbnail will be used as Lectures own thumbnail.

**Comment by gkresic** [comment]
Db schema upgraded.

**IMPORTANT**: do not resolve head unit for every lecture. Instead create a separate method `LectureManager.getHeadUnit(Lecture)` and a separate REST endpoint at URL `/lectures/{id}/head`

**Comment by Genato** [comment]
Becauze "lectures/{id}/thumbnail" should serve static "unit.jpg", need to change part where i throw exception and instead exception return empty Unit object.

**Comment by Genato** [comment]
Covered in commit **LectureResource.getHeadUnit() and LectureManager.getHeadUnit()**.
Finished
