### ISSUE TITLE
Course lectures REST endpoint(s)

### ISSUE THREAD

**Issue by gkresic** [vsite-hr/mentor#16]
Implement `/lectures` and `/lectures/count` services under `CourseResource`. First one should return list of lectures associated with this course (all of them, without paging and in proper order) and second one should return just number of them.

Course's lectures can be already fetched via `/lectures/list` and filtering by course, but these two endpoints should provide more "RESTful" experience.

**Comment by Genato** [comment]
Methods for retrieving lectures and number of lectures for given Course are implemented in `LectureManager{}` as `.list(Course)` and `.count(Course)`
