### ISSUE TITLE
Lecture units REST endpoint(s)

### ISSUE THREAD

**Issue by gkresic** [vsite-hr/mentor#17]
Implement `/units` and `/units/count` services under `LectureResource`. First one should return list of units associated with this lecture (all of them, without paging and in proper order) and second one should return just number of them.

Lecture's units can be already fetched via `/units/list` and filtering by lecture, but these two endpoints should provide more "RESTful" experience.

**Comment by gkresic** [comment]
Db fetch method implemented as `UnitManager.list(Lecture)` and count method as `UnitManager.count(Lecture)`

**Comment by Genato** [comment]
Covered in commit **Issue #17**.
