### ISSUE TITLE
Exception on exception

### ISSUE THREAD

**Issue by Genato** [vsite-hr/mentor#18]
When you provide bad ID for Unit or Lecture, new NotFoundException() is thrown but later in chain another exception is thrown.
**org.jboss.resteasy.spi.UnhandledException: org.jboss.resteasy.core.NoMessageBodyWriterFoundFailure: Could not find MessageBodyWriter for response object of type: hr.vsite.mentor.servlet.rest.MentorError of media type: application/octet-stream**

To reproduce this try this links: 
http://localhost:1800/api/units/b8ebe73e-a476-11e6-aedd-4485006d0fd7/thumbnail
http://localhost:1800/api/units/b8ebe73e-a476-11e6-aedd-4485006d0fd7/content
http://localhost:1800/api/lectures/200ceefa-a476-11e6-aedd-4485006d0fd7/thumbnail

Note:
ID-s are intentionally wrong (if you what to try with exiting ID-s just replace last number "7" with "8" on all three ID-s)

**Comment by gkresic** [comment]
Fixed
