### ISSUE TITLE
Keywords in Lectures

### ISSUE THREAD

**Issue by gkresic** [vsite-hr/mentor#9]
Add "keywords" attribute to Lectures (see Units for implementation details)

**Comment by gkresic** [comment]
Db schema updated.

For manipulating SQL arrays in JDBC see:

[java.sql.Connection.createArrayOf](http://docs.oracle.com/javase/8/docs/api/java/sql/Connection.html#createArrayOf-java.lang.String-java.lang.Object:A-)

[java.sql.ResultSet.getArray](http://docs.oracle.com/javase/8/docs/api/java/sql/ResultSet.html#getArray-java.lang.String-)

For example usage, see `UnitManager.fromResultSet`.

**Comment by Genato** [comment]
Added keywords to Lecture.Java, LectureManager.insert() and LectureManager.update().
